vars:
  - config/loc/params.yaml
stages:
  download:
    cmd: python -m src.pipelines.get_data ${download.url}
    deps:
      - src/pipelines/get_data.py
    outs:
      - artifacts/data/raw/data.csv

  preprocess:
    cmd: python -m src.pipelines.features
    deps:
      - src/pipelines/features.py
      - artifacts/data/raw/data.csv
    outs:
      - artifacts/data/processed/test_data.csv
      - artifacts/data/processed/train_data.csv

  train:
    cmd: python -m src.pipelines.train
    deps:
      - src/pipelines/train.py
      - artifacts/data/processed/test_data.csv
      - artifacts/data/processed/train_data.csv
    outs:
      - artifacts/models/model.joblib