[tool.poetry]
name = "my_project"
version = "0.1.0"
description = "Descricao do projeto"
authors = ["Henrique <henrique.tostes@a3data.com.br>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.25.1"
pandas = "^2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pre-commit = "^3.7.0"
flake8 = "6.1.0"
black = "23.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
skip-string-normalization = true

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
