FROM public.ecr.aws/lambda/python:3.10

RUN pip install poetry

COPY pyproject.toml poetry.lock* ./

# Configurar o Poetry para não criar virtualenv
RUN poetry config virtualenvs.create false

# Verificar configuração do Poetry
RUN poetry config --list

RUN poetry install --no-dev

COPY artifacts/ artifacts/
COPY deployment/lambda/app/lambda_function.py ./
COPY src/ src/
COPY config/ config/

CMD ["lambda_function.lambda_handler"]
