name: Pipeline de Testes
on:
  push:
    branches:
      - teste_pipeline
  pull_request:
    branches:
      - teste_pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar ruff
      run: ruff check .

    - name: Verificar formatação com black
      run: black --check .

    - name: Executar bandit
      run: bandit -r .

    # - name: Executar testes unitarios
    #   run: pytest --cov=.
