name: Pipeline de Testes

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Verificar código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Poetry
      run: pip install poetry

    - name: Instalar dependências
      run: poetry install

    - name: Executar testes unitários
      run: poetry run pytest --cov=.

