name: Pipeline de Qualidade de Código
on:
  push:
    branches:
      - teste_pipeline
  pull_request:
    branches:
      - teste_pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Verificar código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Poetry
      run: pip install poetry

    - name: Instalar dependências
      run: poetry install

    - name: Executar ruff check
      run: poetry run ruff check .

    - name: Formatando código com ruff
      run: poetry run ruff format .

    - name: Verificar formatação com black
      run: poetry run black --check .

    - name: Executar bandit
      run: poetry run bandit -r . --skip B101